---
title: "Übungsaufgaben statistische Qualitätskontrolle"
output: html_notebook
---

# Pre-Processings
```{r}
C_p_func <- function(go, gu, sd){ (go - gu) / (6 * sd) }
C_pk_func <- function(go, gu, sd, mu){ min( (go - mu)/(3*sd), (mu - gu)/(3*sd) )}

C_conf_func <- function(n, alpha, C, centered = TRUE){
  if(centered){
  UG <- C * sqrt( qchisq(alpha/2, df = n -1) / (n - 1) ) 
  OB <- C * sqrt( qchisq(1- alpha/2, df = n -1) / (n - 1) ) 
  
  cat("UG = ", UG, "\t", "OB = ", OB)
  return(list(UG = UG, OG = OB))
  }
  else{
  UG <- C * (1 - qnorm( 1 - alpha/2) * sqrt( 1 / (9 * n * C^2) + 1 / (2 * n - 2) ))
  OB <- C * (1 + qnorm( 1 - alpha/2) * sqrt( 1 / (9 * n * C^2) + 1 / (2 * n - 2) ))
  
  cat("UG = ", UG, "\t", "OB = ", OB)
  return(list(UG = UG, OG = OB))
  }
}
```


```{r}
tmp <- C_conf_func(n = 20, alpha = 0.05, C = 1.2579, centered = TRUE)
```


# Aufgabe 1

```{r}
n <- 40 
Xbar <- 10.01
S <- 0.02
gu <- 9.9
go <- 10.1
alpha <- 0.05
```
**Prozessfaehigkeitsindex $\hat{C}_p$**
```{r}
C_p <- C_p_func(go= go, gu = gu, sd = S)
paste("C_p = ", round(C_p,2))
```
**Konfidenzintervall**
```{r}
error <- qnorm(1-alpha/2) * S / sqrt(n)
Wu <-  Xbar - error
Wo <- Xbar + error
paste(c("Wu = ", "Wo = "),c( round(Wu, 2), round(Wo, 2)) )
```

***

# Aufgabe 2
## (a) $\bar{X}$ - Karte: "Laenge von Nieten"

```{r}
n <- 20
Xbar <- 20.08
S <- 0.053
gu <- 19.8
go <- 20.2
```

**Prozessfaehigkeitsindex $\hat{C}_p$**
```{r}
C_p <- C_p_func(go = go, gu = gu, sd = S)
paste("C_p = ", round(C_p,2))
C_p_conf <- C_conf_func(n = n, alpha = alpha, C = C_p, centered = TRUE)
```


**Prozessfaehigkeitsindex $\hat{C}_{pk}$**
```{r}
C_pk <- C_pk_func(go = go, gu <- gu, sd = S, mu <- Xbar)
paste("C_pk = ", round(C_pk,2))
C_pk_conf <- C_conf_func(n = n, alpha = alpha, C = C_pk, centered = FALSE)
```









